name: build

on:
 workflow_dispatch:

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - name: mkdir
      run: mkdir /home/runner/yes
    - name: cd
      run: cd /home/runner/yes
    - name: checkout repo
      uses: actions/checkout@main
    - name: build application
      run: make
    - name: cp
      run: cp -r * /home/runner/yes/
    - uses: actions/upload-artifact@v3
      with:
       name: compiled_file
       path: /home/runner/yes/
